project:
  type: website

website:
  title: "ghasebe"
  navbar:
    # logo: "images/circle-nodes-solid.svg"
    right:
      - teaching.qmd
      # - about.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



