baseURL = "https://ghasebe.github.io"
languageCode = "en-us"
title = "ghasebe's blog"
copyright = "Georg Hasebe"
# theme = "cactus"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "solarized-light"
    tabWidth = 4

[params]
  colortheme = "custom" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default

  # Home page settings
  mainSection = "posts"
  mainSectionTitle = "Posts"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  tagsOverview = false
  showProjectsList = false

  dateFormat = "02-01-2006"

  # Post page settings
  show_updated = true # default
  showReadTime = false # default

  [params.comments]
    enabled = false

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/ghasebe"
  [[params.social]]
    name = "email"
    link = "gy.hasebe@gmail.com"
