---
title: "Resources"
published-title: "" 
---

## Exam
- [XYQuadrats AnD Survival Guide](https://xyquadrat.ch/eth/and-survival-guide/). He also has a few other posts you might be interested in!
- [PVW Scripts](https://vis.ethz.ch/de/services/pvw-scripts/). Very useful for exam preparation.
- [Collection of old exams](https://exams.vis.ethz.ch/). Very useful for exam preparation. Also contains files from students (e.g. notes, summaries).
- [Cheatsheets/Summaries](https://n.ethz.ch/~dcamenisch/summaries/). Cheatsheet inspiration.

## General
- My How To Guide for Asymptotics: [PDF](asymptotics.pdf), [Overleaf](https://www.overleaf.com/read/qqyngzqrwkzv)
- [A collection of weekly summaries from past semesters](https://n.ethz.ch/~mschlegel/and22/algo2.html).
- [D-INFK discord server](https://discord.gg/DQ3d4beE). A big discord server with a lot of interesting information, many TAs and helpful students.
- [Lecture Material from past semesters (polybox)](https://polybox.ethz.ch/index.php/s/WXf1p3ODpDdpnRH). I think it is no longer maintained, but still useful.
- [Algorithm visualisation](https://www.cs.usfca.edu/~galles/visualization/Algorithms.html). Very useful getting intution on algorithms. I used this for AVL tree exercises.
- [William Fiset on YouTube](https://www.youtube.com/@WilliamFiset-videos). He makes some good DP-related videos. He also has an amazing [github repo](https://github.com/williamfiset/Algorithms) containing many Java algorithms!
- [My Java algorithms github repo](https://github.com/ghasebe/java-algorithms). Sadly incomplete, but I still considered it helpful during my exam prepartion.
- [Gent Serifis AnD Cheatsheet](ADCheatsheet.pdf). Gent was TA for this course as well and was kind enough to share all his files with me. Thank you Gent!
- [Wolfram Alpha](https://www.wolframalpha.com/). A powerful tool very helpful for math.
- [Derivative Calculater](https://www.derivative-calculator.net/). Very helpful for calculating derivatives. (There is also an integral version).
- [MatrixCalc](https://matrixcalc.org/). Online matrix calculator. Very helpful for Linear Algebra. 
- [Desmos Graphing Calculator](https://www.desmos.com/calculator). Online graphing calculator for quick graphing.

## Books
- [Introduction to Algorithms](https://g.co/kgs/m1w8ua), by Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, and Clifford Stein. It's a very famous, very good book. I used it as a reference to supplement the official lecture material (e.g. for matrix chain multiplication).