---
title: "Algorithms and Data Structures"
description: "Teaching Assistant at ETH Zurich."
semester: "Fall Semester 2024"
format:
  html:
    template-partials:
      - title-block.html
listing:
  id: class-material
  contents: weeks 
  sort: "date desc"
  type: grid 
  categories: false
  sort-ui: false 
  filter-ui: false
  image-placeholder: "placeholder.png"
page-layout: article 
title-block-banner: false 
# comments:
#   giscus: 
#     repo: ghasebe/ghasebe.github.io
---

```{=html}
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" data-bs-toggle="tab" href="#information" aria-selected="true" role="tab">Information</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Links</a>
    <div class="dropdown-menu" style="">
      <a class="dropdown-item" href="https://moodle-app2.let.ethz.ch/course/view.php?id=23362">Moodle</a>
    </div>
  </li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active show" id="information" role="tabpanel">
    <p>Hi, I'm Georg!👋🏼</p>
    <p>I teach <strong>Group 9 (German)</strong> on <strong>Mondays at 09:15 in <a href="https://ethz.ch/staffnet/en/service/rooms-and-buildings/rectorate-rooms/pictures/eta-etf-etz.html#par_slideshow_9">ETZ H 91</a></strong>.
  </div>
</div>
```

### Week 13

**Upcoming Session: Longest Palindromic Subsequence (Fall 2020 Exam)**

Next Monday (9th December), we'll dedicate part of the exercise class to solving the DP problem *Longest Palindromic Subsequence* (Fall 2020 exam). If you have time, feel free to look at the problem and try implementing it yourself using the files I've provided -- but no worries if you don't, this is just meant to help you prepare at your own pace.

After we cover the quiz solutions and the exercise sheet as usual, we'll work through this DP problem together, and I'll code the solution live once we've solved it.

You can look up the solution in advance if you want to, but I highly recommend giving it a shot yourself first to get the most out of Monday's session and deepen your understanding of DP.

In case you have questions, feel free to contact me.

- [Longest Palindromic Subsequence Task Description](lps.pdf)
- [Build It Yourself Locally](lps_code.zip)

*The task description and files were taken from CodeExpert. On IntelliJ, I had to add an environment variable `ACTION=run` in the edit configurations to display the output of the `compareTo` method.*

### Week 8

- [Dynamic Progamming II In-Class Notes](week_8_in-class_notes.pdf)

### Week 6

- [Height of Binary Decision Trees and Indeterminate Forms](w06.pdf)
- [Algorithms Implementations](https://github.com/ghasebe/java-algorithms)

### Week 2

- [Math Basics for Asymptotic Analysis](math_recap.pdf)

<!-- ### Class Material
::: {#class-material}
::: -->