---
title: "Algorithms and Probability"
description: "Teaching Assistant at ETH Zurich."
semester: "Spring Semester 2025"
format:
  html:
    template-partials:
      - title-block.html
listing:
  id: class-material
  contents: weeks 
  sort: "date desc"
  type: grid 
  categories: false
  sort-ui: false 
  filter-ui: false
  image-placeholder: "placeholder.png"
page-layout: article 
title-block-banner: false 
# comments:
#   giscus: 
#     repo: ghasebe/ghasebe.github.io
---

```{=html}
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" data-bs-toggle="tab" href="#information" aria-selected="true" role="tab">Information</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Links</a>
    <div class="dropdown-menu" style="">
      <a class="dropdown-item" href="https://moodle-app2.let.ethz.ch/course/view.php?id=24833">Moodle</a>
    </div>
  </li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active show" id="information" role="tabpanel">
    <p>Hi, I'm Georg!👋🏼</p>
    <p>I teach <strong>Group 9 (German)</strong> on <strong>Thursdays at 16:15 in <a href="https://ethz.ch/staffnet/en/service/rooms-and-buildings/rectorate-rooms/pictures/hg.html#par_slideshow_30">HG G 26.5</a></strong>.
    <p>The resources on this website are not part of the official lecture material. No guarantees for correctness or completeness. Please let me know if you find any mistakes!</p>
  </div>
</div>
```

### Week 15

Ascension Day.

### Week 14

- [Problem Description (Game of Skill)](a-game-of-skill.pdf)
- [Programming Solution](https://gist.github.com/ghasebe/8b8e0be1d8d8b581a213433b35787f40)

### Week 13

- [Week 13 Slides](anp-w13-25_presented.pdf)

### Week 12

- [Week 12 Slides](anp-w12-25_presented.pdf)

### Week 11

Labour Day.

### Week 10

Week after Easter.

### Week 9

No slides.

### Week 8

- [Week 8 Slides](anp-w08-25_presented.pdf)

### Week 7

- [Week 7 Slides](anp-w07-25_presented.pdf)

### Week 6

- [Week 6 Slides](anp-w06-25_presented.pdf)

### Week 5

- [Week 5 Slides](anp-w05-25_presented.pdf)
- [In-Class Probability Exercises Solutions](anp-w05-25_notes.pdf)

### Week 4

- [Week 4 Slides](anp-w04-25_presented.pdf)

### Week 3

- [Week 3 Slides](anp-w03-25_presented.pdf)
- [In-Class Matching Proof](anp-w03-25_notes_matching.pdf)

**Additional Material:**

- [Hall's Theorem Slides (Not Covered)](anp-w03-25_hall.pdf)
- [Hall's Theorem Proof Notes (Not Covered)](anp-w03-25_notes_hall.pdf)

### Week 2

- [Week 2 Slides](anp-w02-25_presented.pdf)

### Week 1

- [Algorithms and Data Structures Recap](and-recap.pdf)